name: stundart_workspace
description: A Dart monorepo workspace for StunDart packages
version: 1.0.0
publish_to: none

environment:
  sdk: '^3.9.4'

workspace:
  - packages/Stun
  - packages/StunDartTests

dev_dependencies:
  melos: ^7.3.0

melos:
  scripts:
    barrels:
      run: melos exec --ignore=StunDartTests -- dart run build_runner build
      description: Generate barrel files (indexes) for all packages using build_runner.
