name: stundart_tests
description: Test suite for the StunDart package
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '^3.9.4'

dev_dependencies:
  build_runner: ^2.13.0
  config_manager: any
  lints: ^6.0.0
  test: ^1.31.0
  stun: any
  singleton_manager: any
